name: Cloud-CI


permissions:
  contents: write    # Permission to push the updated deployment.yml back to Git
  packages: write    # Permission to push the Docker image to GHCR


on:
  pull_request:
    branches: [ temp, dev ]


jobs:
  
  # JOB 1: Verification (Always runs for PRs and Pushes)
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim
    steps:
      - &github-context
        name: Dump GitHub Context
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Reference: ${{ github.ref }}"
          echo "Head Ref: ${{ github.head_ref }}"
          echo "Base Ref: ${{ github.base_ref }}"

      - name: Update packages
        run: |
          pip install --upgrade pip
      
      - name: Checkout Code
        uses: actions/checkout@v4  # This pulls the code INTO the container's workspace

      - name: Where am I?
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in this directory:"
          ls -a

      - name: Install and Test
        run: |
          cd app
          pip install -e .[dev]
          pytest


  # JOB 2: Update Manifest (Only runs for PRs to temp)
  update-manifest:
    needs: build-and-test
    if: github.event_name == 'pull_request' && github.base_ref == 'temp'
    runs-on: ubuntu-latest
    steps:
      - *github-context
  
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # This ensures we are on the branch, not a detached SHA
          ref: ${{ github.head_ref }}
          # Fetch all history so we can push back
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/dummy-app:${{ github.sha }}
          docker build -t $IMAGE_ID ./app
          docker push $IMAGE_ID

      - name: Update GitOps Manifest
        run: |
          sed -i "s|\(image: ghcr.io/${{ github.repository_owner }}/dummy-app:\).*|\1${{ github.sha }}|g" k8s/deployment.yml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/deployment.yml
          git commit -m "chore: deploy image ${{ github.sha }} [skip ci]"
          # Explicitly push to the PR branch
          git push origin HEAD:${{ github.head_ref }}
